// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkXWl9Vjls2RmQZfw1Z0zT_Pa2McTrLWg',
    appId: '1:292017223369:web:e4baf1e00e06e7fcd93f18',
    messagingSenderId: '292017223369',
    projectId: 'flutter-firebase-crud-2aa51',
    authDomain: 'flutter-firebase-crud-2aa51.firebaseapp.com',
    storageBucket: 'flutter-firebase-crud-2aa51.appspot.com',
    measurementId: 'G-WZVVL4MT5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa0sufZjAZ5lBY_xJamPg2pXga5M1C4JA',
    appId: '1:292017223369:android:976c236e12796529d93f18',
    messagingSenderId: '292017223369',
    projectId: 'flutter-firebase-crud-2aa51',
    storageBucket: 'flutter-firebase-crud-2aa51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyColuYgbrDVWdN1hpKih6zC-un19ur-0uE',
    appId: '1:292017223369:ios:e820a62a8d4c9cb1d93f18',
    messagingSenderId: '292017223369',
    projectId: 'flutter-firebase-crud-2aa51',
    storageBucket: 'flutter-firebase-crud-2aa51.appspot.com',
    iosClientId: '292017223369-5p1ivibg49ef5ki3iefb8dr46pcsu0vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyColuYgbrDVWdN1hpKih6zC-un19ur-0uE',
    appId: '1:292017223369:ios:e820a62a8d4c9cb1d93f18',
    messagingSenderId: '292017223369',
    projectId: 'flutter-firebase-crud-2aa51',
    storageBucket: 'flutter-firebase-crud-2aa51.appspot.com',
    iosClientId: '292017223369-5p1ivibg49ef5ki3iefb8dr46pcsu0vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );
}
